glamazer/artists/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^how_it_works/', TemplateView.as_view(template_name="core/how_it_works_artists.html"), name='artists_HIW'),
    url(r'^change_password/(?P<email_token>.*)', 'glamazer.users.views.change_password', name='change_password'),
    url(r'^forgotten_password/', 'glamazer.users.views.forgotten_password', name='forgotten_password'),
    url(r'^sign_up/$', 'glamazer.artists.views.sign_up', name='artists_sign_up'),
    url(r'^sign_up/facebook$', 'glamazer.artists.views.facebook_registration', name='artists_sign_up_facebook'),
    url(r'^profile/$', 'glamazer.artists.views.profile', name='artists_profile'),
    url(r'^profile/(?P<artist_id>.*)/(?P<name>.*)$', 'glamazer.artists.views.profile', name='profile_artist'),
    url(r'^settings/profile$', 'glamazer.artists.views.edit', name='edit_artist_profile'),
    url(r'^settings/account$', 'glamazer.artists.views.account', name='edit_artist_account'),
    url(r'^settings/payments$', 'glamazer.artists.views.payments', name='artist_payments'),
    url(r'^settings/policy$', 'glamazer.artists.views.cancellation_policy', name='artist_cancellation_policy'),
    url(r'^management/listings$', 'glamazer.artists.views.all_listings', name='all_listing'),
    url(r'^management/schedule$', 'glamazer.artists.views.schedule', name='artist_schedule'),
    url(r'^management/calendar/$', 'glamazer.artists.views.calendar', name='artists_calendar'),
    url(r'^management/statistic/$', TemplateView.as_view(template_name="artists/management/stats.html"), name='artists_statistic'),
    url(r'^settings/widgets$', 'glamazer.widget.views.create_widget', name='artist_widgets'),
    url(r'^upload/$', 'glamazer.artists.views.upload', name='upload'),
    url(r'^bookings/$', 'glamazer.artists.views.bookings', name='artists_bookings'),
    url(r'^bookings/report$', 'glamazer.users.views.report_problem', name='artists_report_booking'),
    url(r'^wallet/$', 'glamazer.artists.views.wallet', name='artists_wallet'),
    url(r'^withdraw/$', 'glamazer.artists.views.withdraw', name='artists_withdraw'),
    url(r'^notifications/$', 'glamazer.notifications.views.show_notifications', name='artist_notifications'),
    url(r'^get_chart_info/$', 'glamazer.artists.views.get_chart_info', name='get_chart_info'),
    url(r'^salon_suspend/(?P<salon_id>.*)$', 'glamazer.artists.views.salon_suspend', name='salon_suspend'),
    url(r'^salon_apply/(?P<salon_id>.*)$', 'glamazer.artists.views.salon_apply', name='salon_apply'),
)

glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^hairstyle/', 'glamazer.core.views.base', name='hair'),
    url(r'^nails-design/', 'glamazer.core.views.base', name='nails'),
    url(r'^make-up/', 'glamazer.core.views.base', name='make_up'),
    url(r'^style/', 'glamazer.core.views.base', name='style'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^terms/', TemplateView.as_view(template_name="core/terms.html"), name='terms'),
    url(r'^imprint/', TemplateView.as_view(template_name="core/imprint.html"), name='imprint'),
    url(r'^privacy/', TemplateView.as_view(template_name="core/privacy.html"), name='privacy'),
    url(r'^faq/', TemplateView.as_view(template_name="core/faq.html"), name='faq'),
    url(r'^about_us/', TemplateView.as_view(template_name="core/about_us.html"), name='about_us'),
    url(r'^contacts/', TemplateView.as_view(template_name="core/contact_us.html"), name='contacts'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^salons/', include('glamazer.salons.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^widget/', include('glamazer.widget.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^get_hint/', 'glamazer.core.views.get_hint', name='get_hint'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='paypal_payment'),
    url(r'^send_feedback/$', 'glamazer.users.views.send_feedback', name='send_feedback'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/artists/models.py
import requests

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from glamazer.salons.models import Salon
from glamazer.notifications.models import Notification
from glamazer.settings import MEDIA_ROOT, STYLE_INDEXES, HOURS, CURRENCY

POLICY_STATUS = ((0, 'Pending',), (1, 'Current',), (2, 'Was Approved',), (3, 'Rejected',))


class Artist(models.Model):
    facebook_id = models.CharField(max_length=20, blank=True, null=True)
    user = models.OneToOneField(User, unique=True)
    salon = models.ForeignKey(Salon, null=True, blank=True)
    lng = models.FloatField(default=0)
    lat = models.FloatField(default=0)
    description = models.TextField(null=True)
    currency = models.CharField(max_length=8, choices=CURRENCY, default='USD')
    avatar = models.CharField(max_length=128, blank=True, null=True)
    custom_fee = models.IntegerField(blank=True, null=True)
    mobile_number = models.CharField(max_length=128, blank=True, null=True)
    money = models.FloatField(default=0)
    style = models.IntegerField(default=0, choices=STYLE_INDEXES)
    rating = models.FloatField(default=5)
    is_activated = models.BooleanField(default=True)
    enable_emails = models.BooleanField(default=True)
    enable_sms = models.BooleanField(default=False)
    step = models.IntegerField(default=0)
    waiting_for_hired = models.BooleanField(default=False)  # if true => The artist waiting for salon approving
    waiting_for_fired = models.BooleanField(default=False)  # if false => The artist waiting for salon approving for suspend

    def get_avatar(self):
        try:
            return MEDIA_ROOT + self.avatar[7:]
        except:
            return ''

    def get_salon_avatar(self):
        try:
            return MEDIA_ROOT + self.salon.avatar[7:]
        except:
            return ''

    def get_name(self):
        return self.user.first_name

    def get_salon_name(self):
        try:
            return self.salon.user.first_name
        except:
            return None

    def get_style(self):
        return STYLE_INDEXES[self.style][1]

    def get_address(self):
        url = 'http://maps.googleapis.com/maps/api/geocode/json?latlng={0},{1}&sensor=false'.format(self.lat, self.lng)
        request = requests.get(url)
        json_results = request.json()
        try:
            address = json_results['results'][6]['formatted_address']
        except:
            address = 'undefined'
        return address

    def get_notification_count(self):
        '''get only the notifications count, whithout evaluate the query'''
        notification_count = Notification.objects.filter(receiver=self.user, is_readed=False).count()
        return notification_count

    def get_notifications(self, limit=0):
        '''get all notifications for current instance and make them readed'''
        if limit:
            notifications = Notification.objects.filter(receiver=self.user)[:limit]
        else:
            notifications = Notification.objects.filter(receiver=self.user)

        return notifications

    def get_avatar_tag(self):
        return '<img src="%s" style="border-radius: 999px" />' % self.avatar

    def get_step(self):
        if not self.step:
            return 'Finished'
        else:
            return self.step

    def get_cancellation_rate(self):
        cr = CancellationRate.objects.get(artist=self)
        try:
            rate = (cr.cancelled*100)/(cr.approved)
        except:
            rate = 0
        return rate

    def salon_link(self):
        url = "None"
        try:
            url = '<a href="%s">%s</a>' % (reverse(("admin:salons_salon_change"), args=(self.salon_id, )), self.salon.user.first_name)
        except:
            pass

        return url

    def save(self, force_insert=False, force_update=False, **kwargs):
        if not self.id:
            super(Artist, self).save(force_insert, force_update)
            ArtistPolicy.objects.create(artist=self, cancellation_policy_id=1, status=1)
            CancellationRate.objects.create(artist=self)
        else:
            super(Artist, self).save(force_insert, force_update)

    salon_link.allow_tags = True
    salon_link.short_description = "Salon"

    get_avatar_tag.short_description = 'Avatar'
    get_avatar_tag.allow_tags = True

    get_name.allow_tags = True
    get_name.short_description = "Name"

    get_step.allow_tags = True
    get_step.short_description = "Step"

    def __str__(self):
        return self.user.first_name


class Busy(models.Model):
    artist = models.ForeignKey(Artist)
    comment = models.CharField(max_length=255, blank=True, null=True)
    start_time = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)


class WorkTime(models.Model):
    artist = models.ForeignKey(Artist)
    mon_start = models.IntegerField(blank=True, null=True, default="0")
    mon_end = models.IntegerField(blank=True, null=True, default="24")
    tues_start = models.IntegerField(blank=True, null=True, default="0")
    tues_end = models.IntegerField(blank=True, null=True, default="24")
    wed_start = models.IntegerField(blank=True, null=True, default="0")
    wed_end = models.IntegerField(blank=True, null=True, default="24")
    thurs_start = models.IntegerField(blank=True, null=True, default="0")
    thurs_end = models.IntegerField(blank=True, null=True, default="24")
    fri_start = models.IntegerField(blank=True, null=True, default="0")
    fri_end = models.IntegerField(blank=True, null=True, default="24")
    sat_start = models.IntegerField(blank=True, null=True, default="-1")
    sat_end = models.IntegerField(blank=True, null=True, default="-1")
    sun_start = models.IntegerField(blank=True, null=True, default="-1")
    sun_end = models.IntegerField(blank=True, null=True, default="-1")

    def get_serialiazed(self):
        return [[self.mon_start, self.mon_end],
                [self.tues_start, self.tues_end],
                [self.wed_start, self.wed_end],
                [self.thurs_start, self.thurs_end],
                [self.fri_start, self.fri_end],
                [self.sat_start, self.sat_end],
                [self.sun_start, self.sun_end]]

    def monday(self):
        if self.mon_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.mon_start], HOURS[self.mon_end])

    def tuesday(self):
        if self.tues_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.tues_start], HOURS[self.tues_end])

    def wednesday(self):
        if self.wed_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.wed_start], HOURS[self.wed_end])

    def thursday(self):
        if self.thurs_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.thurs_start], HOURS[self.thurs_end])

    def friday(self):
        if self.fri_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.fri_start], HOURS[self.fri_end])

    def saturday(self):
        if self.sat_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.sat_start], HOURS[self.sat_end])

    def sunday(self):
        if self.sun_start == -1:
            return _("Not working!")
        else:
            return '{0}-{1}'.format(HOURS[self.sun_start], HOURS[self.sun_end])


class CancellationRate(models.Model):
    artist = models.ForeignKey(Artist)
    cancelled = models.IntegerField(default=0)
    approved = models.IntegerField(default=0)


class CancellationPolicy(models.Model):
    cancellation_type = models.CharField(max_length=128, default="Custom")
    days_before = models.IntegerField()
    percent = models.IntegerField()
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.cancellation_type


class ArtistPolicy(models.Model):
    artist = models.ForeignKey(Artist)
    cancellation_policy = models.ForeignKey(CancellationPolicy)
    last_change = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0, choices=POLICY_STATUS)

    def artist_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:artists_artist_change"), args=(self.artist_id, )), self.artist.user.first_name)
        return url

    def cancellation_policy_link(self):
        url = '<a href="%s">%s</a>' % (
            reverse(("admin:artists_cancellationpolicy_change"),
            args=(self.cancellation_policy_id, )),
            self.cancellation_policy.cancellation_type
        )
        return url

    def save(self, force_insert=False, force_update=False, **kwargs):
        super(ArtistPolicy, self).save(force_insert, force_update)
        if self.id:
            if self.status == 1:
                ArtistPolicy.objects.filter(artist=self.artist, status=1).exclude(id=self.id).update(status=2)

    artist_link.allow_tags = True
    artist_link.short_description = "Artist"

    cancellation_policy_link.short_description = 'Cancellation Type'
    cancellation_policy_link.allow_tags = True

templates/artists/bookings.html
{% extends "master.html" %}
{% load thumbnail %}
{% load i18n %}

    {% block meta %}
        <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Bookings" %}</title>
    {% endblock meta %}

    {% block content %}
    <script type="text/javascript" src="{{STATIC_URL}}js/moment.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/qtip.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.0.0.js"></script>

<div id="content">
    <div class="header">
        <span>{% trans "BOOKINGS" %}</span>
    </div>

    <div class="column">
        <table id="bookings">
            <thead>
                <tr>
                    <th>#</th>
                    <th>{% trans "ORDER ID" %}</th>
                    <th>{% trans "DATE" %}</th>
                    <th>{% trans "LISTING" %}</th>
                    <th>{% trans "ORDERED BY" %}</th>
                    <th>{% trans "AMOUNT" %}</th>
                    <th>{% trans "STATUS" %}</th>
                    <th>{% trans "ACTION" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for b in bookings %}
                <tr data-number="{{ b.id }}" class="{% if b.id|slugify == request.GET.show %} active{% endif %}{% cycle 'dark' 'light' %}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ b.id }}</td>
                    <td class="start_time_{{ b.id }}">

                    </td>
                    <td class="listing_view listing_view_{{b.id}}">
                        <a href="{% url 'listing' b.listing_id b.title %}">{{b.title}}</a>
                    </td>
                    <td>
                        <a href="{% url 'profile_user' b.client.id b.client.user.first_name %}">
                            {% thumbnail b.client.get_avatar "55x55" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{b.client.user.first_name}}" width="55" height="55" style="border: 2px solid white; border-radius: 999px; width: 45px; height: 45px;">
                            {% empty %}
                                <img src="{{ STATIC_URL }}img/default.png" alt="avatar" width="55" height="55" style="border: 2px solid white; border-radius: 999px">
                            {% endthumbnail %}
                        </a>
                    </td>
                    <td>
                        {{ b.get_currency_display }} {{ b.price|floatformat:-3 }}
                    </td>
                    <td>
                        {{ b.get_status_display }}
                        <script type="text/javascript">
                            start_time = {{b.start_time}}; //get start time
                            time_now = Math.floor(new Date().getTime() / 1000); //now in UTC seconds
                            delta_time = start_time - time_now; // delta time
                            x_days_in_seconds = 273600; // 3 days in seconds
                            b_id = '{{ b.id }}'; // booking id
                            if(delta_time < x_days_in_seconds){
                                $('.start_time_' + b_id).closest('tr').addClass('dialog');
                            }
                            start_time = moment(start_time*1000).format('h:mm a   MM/DD/YYYY');
                            $('.start_time_' + b_id).text(start_time);
                            $('.listing_view_' + b_id + ' a').qtip({
                              content: '{% thumbnail b.listing.get_picture "200x112" crop="center" as im %}<img src="{{ im.url }}" style="width: 222px;" alt="listing">{% endthumbnail %}',
                              style: { width: { min: 222 } }
                            });
                        </script>
                    </td>
                    <td>
                        {% if b.status < 2 %}
                            {% if b.status == 0 %}
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{b.id}}" name="sn_approve">
                                <textarea name="" id="" cols="30" rows="10" class="hidden"></textarea>
                                <input type="submit" class="new_button green nb_hover" value="{% trans 'Approve' %}">
                            </form>
                            {% endif %}
                            <form class="cancel" method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{b.id}}" name="sn">
                                <input type="submit" class="new_button red nb_hover" value="{% trans 'Cancel' %}">
                            </form>
                        {% elif b.status == 3 %}
                            <form class="report" method="POST" action="{% url 'artists_report_booking' %}">
                                {% csrf_token %}
                                <input type="hidden" value="{{b.id}}" name="sn">
                                <textarea name="comment" id="" cols="30" rows="10" class="hidden"></textarea>
                                <input type="submit" class="new_button red nb_hover" value="{% trans 'Report' %}">
                            </form>
                        {% else %}
                            None
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% if bookings|length == 0 %}
                <tr class="pagination">
                    <td colspan='8'>
                        <div class="step-links">
                            {% blocktrans %}
                            Currently you don't have any bookings.
                            {% endblocktrans %}
                        </div>
                    </td>
                </tr>
                {% elif bookings.has_previous or bookings.has_next %}
                <tr class="pagination">
                    <td colspan='8'>
                        <div class="step-links">
                            {% if bookings.has_previous %}
                                <a href="?page={{ bookings.previous_page_number }}">&lt;</a>
                            {% endif %}

                            <span class="current">
                            {% for page in bookings.paginator.page_range %}
                                <a href="?page={{page}}" class='page{% if page == 0 or page == bookings.number %} active{% endif %}'>{{ page }}</a>
                            {% endfor %}
                            </span>

                            {% if bookings.has_next %}
                                <a href="?page={{ bookings.next_page_number }}">></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
<div class="dialog_box cpolicy" style="display: none">
    <div class="wrapper">
        <div class="head">{% trans "WARNING" %}!<a href="javascript:;">X</a></div>
        <div class="body">
            <div class="text">
                {% blocktrans %}
                Cancelling an appointmnt will increase your cancellation rate and we will remove 10 points from your monthly score.<br/><br/>Are you sure you want to cancel this appointment?
                {% endblocktrans %}
            </div>
            <ul>
                <li class="Yes"><a class="new_button green nb_hover" href="javascript:;">{% trans "Yes" %}</a></li>
                <li class="No"><a class="new_button red nb_hover" href="javascript:;">{% trans "No" %}</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="dialog_box report_problem" style="display: none">
    <div class="wrapper">
        <div class="head">{% trans "REPORT A PROBLEM!" %}<a href="javascript:;">X</a></div>
        <div class="body">
            <div class="text">{% trans "Oh, no! What went wrong?" %}</div>
            <textarea id="id_comment_dummy" cols="30" rows="10" placeholder="{% trans 'Please describe your problem' %}"></textarea>
            <ul>
                <li class="send"><a class="new_button green nb_hover" href="javascript:;">{% trans "Send" %}</a></li>
            </ul>
        </div>
    </div>
</div>
    {% endblock content %}

    {% block scripts %}
    <script type="text/javascript">
        $('.dialog_box').click(function(e){
            if($(e.target).hasClass('dialog_box')){
                $(this).hide();
                flag = 0;
            }
        });

        $('.dialog_box .head a, .dialog_box .body li.No a').click(function(){
            $('.dialog_box').hide();
            flag = 0;
        });

        $('.dialog_box .body li.Yes a').click(function(){
            $('tr[data-number="' + $('.dialog_box').data('number') + '"]').removeClass('dialog').find('.cancel').filter('form').submit();
        });

        $('form.cancel').submit(function(e){
            if ($(this).closest('tr').hasClass('dialog')){
                $('.dialog_box.cpolicy').data('number', $(this).closest('tr').data('number')).show();
                e.preventDefault();
            }
        });

        $('.dialog_box.report_problem .send').click(function(){
            var closest_box = $(this).closest(".dialog_box");
            var text = $(this).closest(".report_problem").find("textarea").val();
            $('tr[data-number="' + closest_box.data('number') + '"]').find('form.report').find("textarea").val(text).end().submit();
        });

        var flag = 0
        $('form.report').submit(function(e){
            if(flag == 0){
                $('.dialog_box.report_problem').data('number', $(this).closest('tr').data('number')).show();
                e.preventDefault();
                flag = 1;
            }
        });
    </script>
    {% endblock scripts %}
</body>
</html>

templates/artists/upload.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Upload Listing" %}</title>
{% endblock meta %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/select2.css">
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/jquery-ui.css">

{% endblock stylesheets %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "ADD NEW LISTING" %}</span>
    </div>

    <div class="column">
        <form  class="login listing_upload" method="POST" enctype="multipart/form-data" data-fee="{{ fee }}">
            {% csrf_token %}
            <div class="left_wrapper">
                <div class="vertical_box photos">
                    <div class="box_title">{% trans "1. Photos" %}</div>
                    <div class="body">
                        <div id="gallery_preview" class="multiple_listing">
                            <ul>
                                
                            </ul>
                        </div>
                        <div class="photos_upload">
                            {% if form.cover.errors %}
                                <div class="wrong_picture">{{ form.cover.errors }}</div>
                            {% endif %}
                            <div class="upload_button">{% trans "Click here to upload picture" %}</div>
                            <input type="file" name="pictures" id="id_picture" class="custom_button active_input" multiple/>
                            {{ form.cover }}
                        </div>
                    </div>
                </div>

                <div class="vertical_box price">
                    <div class="box_title">{% trans "2. Price" %}</div>
                    <div class="body">
                        <div class="price"><label for="" class="main_label">
                            {% if form.price.errors %}
                                {{ form.price.errors }}
                            {% endif %}
                            {% trans "Price" %}</label><br>
                            <span class="currency">{{ request.user.artist.get_currency_display }}</span>
                            {{ form.price }}
                        </div>
                        <div class="recalculate">
                            {% trans "Price after fees" %}: {{ request.user.artist.get_currency_display }}<span class="real_price">0</span><br><br>
                            {% blocktrans %}
                            All fees will be paid by the customer.
                            {% endblocktrans %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="vertical_box description">
                <div class="box_title">{% trans "3. Description" %}</div>
                <div class="body">
                    <ul>
                        <li class="label_container"><label for="" class="main_label">
                            {% if form.title.errors %}
                                {{ form.title.errors }}
                            {% endif %}
                            {% trans "Title" %}</label></li>
                        <li>
                            {{ form.title }}
                        </li>
                        <li class="label_container"><label for="" class="main_label">
                            {% if form.description.errors %}
                                {{ form.description.errors }}
                            {% endif %}
                            {% trans "Description" %}</label></li>
                        <li>
                            {{ form.description }}
                        </li>
                        <li class="label_container duration_gender">
                            <div class="duration">
                                <label for="" class="main_label">
                                {% if form.duration.errors %}
                                    {{ form.duration.errors }}
                                {% endif %}
                                {% trans "Duration" %}</label>{{ form.duration }}
                            </div>
                            <div class="gender">
                                <label for="" class="main_label">
                                {% if form.gender.errors %}
                                    {{ form.gender.errors }}
                                {% endif %}{% trans "Type" %}</label>
                                {{ form.gender }}
                            </div>
                        </li>
                        <li class="clear"></li>
                        <li class="label_container"><label for="" class="main_label">
                            {% if form.tags.errors %}
                                {{ form.tags.errors }}
                            {% endif %}
                            {% trans "Tags" %}</label></li>
                        <li class="tags">
                            {{ form.tags }}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="clear"></div>
            <input type="submit" class="custom_button" value="{% trans "Save" %}">
        </form>
    </div>
</div>

    {% endblock content %}
    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
        <script src="{{STATIC_URL}}js/preview.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/select2.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/upload_listing.js"></script>
    {% endblock scripts %}
</body>
</html>