glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^hairstyle/', 'glamazer.core.views.base', name='hair'),
    url(r'^nails-design/', 'glamazer.core.views.base', name='nails'),
    url(r'^make-up/', 'glamazer.core.views.base', name='make_up'),
    url(r'^style/', 'glamazer.core.views.base', name='style'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^terms/', TemplateView.as_view(template_name="core/terms.html"), name='terms'),
    url(r'^imprint/', TemplateView.as_view(template_name="core/imprint.html"), name='imprint'),
    url(r'^privacy/', TemplateView.as_view(template_name="core/privacy.html"), name='privacy'),
    url(r'^faq/', TemplateView.as_view(template_name="core/faq.html"), name='faq'),
    url(r'^about_us/', TemplateView.as_view(template_name="core/about_us.html"), name='about_us'),
    url(r'^contacts/', TemplateView.as_view(template_name="core/contact_us.html"), name='contacts'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^salons/', include('glamazer.salons.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^widget/', include('glamazer.widget.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^get_hint/', 'glamazer.core.views.get_hint', name='get_hint'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='paypal_payment'),
    url(r'^send_feedback/$', 'glamazer.users.views.send_feedback', name='send_feedback'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/salons/models.py
import requests
import os

from django.db import models
from django.contrib.auth.models import User
from glamazer.notifications.models import Notification
from glamazer.settings import MEDIA_ROOT, STATIC_ROOT, CURRENCY


class Salon(models.Model):
    facebook_id = models.CharField(max_length=20, blank=True, null=True)
    user = models.OneToOneField(User, unique=True)
    lng = models.FloatField(default=0)
    lat = models.FloatField(default=0)
    description = models.TextField(null=True)
    avatar = models.CharField(max_length=128, blank=True, null=True)
    mobile_number = models.CharField(max_length=128, blank=True, null=True)
    money = models.FloatField(default=0)
    currency = models.CharField(max_length=128, choices=CURRENCY, default='USD')
    rating = models.FloatField(default=5)
    is_activated = models.BooleanField(default=False)
    step = models.IntegerField(default=0)
    enable_emails = models.BooleanField(default=True)
    enable_sms = models.BooleanField(default=False)

    def get_avatar(self):
        try:
            return MEDIA_ROOT + self.avatar[7:]
        except:
            return ''

    def get_name(self):
        return self.user.first_name

    def have_artist(self):
        from glamazer.artists.models import Artist
        if Artist.objects.filter(salon=self, is_activated=True).count():
            return True
        else:
            return False

    def get_address(self):
        url = 'http://maps.googleapis.com/maps/api/geocode/json?latlng={0},{1}&sensor=false'.format(self.lat, self.lng)
        request = requests.get(url)
        json_results = request.json()
        try:
            address = json_results['results'][6]['formatted_address']
        except:
            address = 'undefined'
        return address

    def get_all_images(self):
        ''' Try to get all pictures for the salon, if the folder is empty, return '''

        gallery = '{0}salons/{1}/gallery'.format(MEDIA_ROOT, self.id)
        if os.path.isdir(gallery):
            pictures = {}
            for f in os.listdir(gallery):
                pictures[f] = '{0}/{1}'.format(gallery, f)
        else:
            pictures = []
        return pictures

    def get_notification_count(self):
        '''get only the notifications count, whithout evaluate the query'''
        from glamazer.artists.models import Artist
        users = []
        artists = Artist.objects.select_related('user').filter(salon=self)
        for artist in artists:
            users.append(artist.user)

        users.append(self.user)

        notification_count = Notification.objects.filter(receiver__in=users, is_readed=False).count()
        return notification_count

    def get_notifications(self, limit=0):
        '''get all notifications for current instance and make them readed'''
        from glamazer.artists.models import Artist
        users = []
        artists = Artist.objects.select_related('user').filter(salon=self)
        for artist in artists:
            users.append(artist.user)

        users.append(self.user)

        if limit:
            notifications = Notification.objects.filter(receiver__in=users)[:limit]
        else:
            notifications = Notification.objects.filter(receiver__in=users)
        return notifications

    def __str__(self):
        return self.user.first_name

    def get_avatar_tag(self):
        try:
            return '<img src="%s" style="border-radius: 999px" />' % self.avatar
        except:
            return '<img src="%s" style="border-radius: 999px" />' % (STATIC_ROOT+'/img/default.png')

    def get_step(self):
        if not self.step:
            return 'Finished'
        else:
            return self.step

    def get_cancellation_rate(self):
        from glamazer.artists.models import Artist
        artists = Artist.objects.filter(salon=self)
        temp_rate = 0
        for a in artists:
            temp_rate += a.get_cancellation_rate()
        rate = temp_rate/len(artists)
        return rate

    get_avatar_tag.short_description = 'Avatar'
    get_avatar_tag.allow_tags = True

    get_name.allow_tags = True
    get_name.short_description = "Name"

    get_step.allow_tags = True
    get_step.short_description = "Step"

glamazer/salons/forms.py
import os
import re
import string
import random
import shutil
import base64
import math

from io import BytesIO
from PIL import Image

from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils.translation import ugettext as _

from glamazer.core.helpers import get_object_or_None, get_fee
from glamazer.core.notifications import new_artist_to_salon
from glamazer.artists.models import Artist
from glamazer.salons.models import Salon
from glamazer.listings.models import Listing, Tags, ListingTags
from glamazer.settings import STYLE_INDEXES, MEDIA_FOLDER, MEDIA_ROOT, DURATION


class SalonForm(ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())
    password = forms.CharField(widget=(forms.PasswordInput()))
    confirm_password = forms.CharField(widget=(forms.PasswordInput()))

    class Meta:
        model = Salon
        fields = ['confirm_password', ]

    def clean_email(self):

        email = self.cleaned_data['email']
        check_email = User.objects.filter(email=email)

        if check_email:
            raise forms.ValidationError(
                _("A user associated with this email address already exists"))

        return email

    def clean_password(self):

        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not password == confirm_password:
            raise forms.ValidationError(_("Password mismatch"))

        elif len(password) < 6:
            raise forms.ValidationError(_("Password is too short (6 symbols)"))

        elif password.isalpha() or password.isdigit():
            raise forms.ValidationError(_("Password should contain at least one alphabetic and one non-alphabetic character"))

        return password

    def save(self):

        data = self.cleaned_data
        username = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(16))

        new_user = User.objects.create_user(username=username,
                                            first_name=data['name'],
                                            email=data['email'],
                                            password=data['password'],
                                            related_with="salons")

        return new_user


class LocationSalonDetails(forms.Form):
    address = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': _('Enter street address')}))
    lat = forms.CharField(required=False, widget=forms.HiddenInput())
    lng = forms.CharField(required=False, widget=forms.HiddenInput())


class EditSalon(ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput())
    avatar = forms.ImageField(required=False, widget=forms.FileInput())
    description = forms.CharField(required=False, widget=forms.Textarea())
    address = forms.CharField(required=False, max_length=128, widget=forms.TextInput())
    lat = forms.CharField(required=False, widget=forms.HiddenInput())
    lng = forms.CharField(required=False, widget=forms.HiddenInput())
    mobile_number = forms.CharField(required=False)
    cropped_image = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Salon
        exclude = ('money', 'rating', 'avatar', 'user', 'step', 'currency')

    def save(self):

        salon = self.instance
        user = salon.user
        data = self.cleaned_data

        user.first_name = data['name']
        user.save()
        salon.description = data['description']
        salon.address = data['address']
        salon.lat = data['lat']
        salon.lng = data['lng']
        salon.mobile_number = data['mobile_number']
        salon.save()

        my_file = data['cropped_image']

        if my_file:

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(my_file).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(10))

            salon_id = str(salon.id)
            path = '/' + MEDIA_FOLDER + '/salons/{0}/avatar/{1}.jpeg'.format(salon_id, hash_name)
            full_path = MEDIA_ROOT + 'salons/{0}/avatar/{1}.jpeg'.format(salon_id, hash_name)
            salon.avatar = path
            salon.save()

            #if the folder doesn't exist, create one
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)
            else:
                shutil.rmtree(d)
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
            im.save(full_path, 'JPEG')

        return salon


class AddArtist(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput())
    name = forms.CharField(required=True, widget=forms.TextInput())
    style = forms.ChoiceField(widget=forms.Select(), choices=STYLE_INDEXES)
    avatar = forms.ImageField(required=False, widget=forms.FileInput())
    cropped_image = forms.CharField(required=False, widget=forms.HiddenInput())
    description = forms.CharField(widget=forms.Textarea())

    def save(self, salon):

        data = self.cleaned_data
        my_file = data['cropped_image']

        password = ''.join(random.choice(string.ascii_lowercase + string.digits)
                   for x in range(6))
        username = ''.join(random.choice(string.ascii_lowercase + string.digits)
                   for x in range(16))

        new_user = User.objects.create_user(username=username,
                                            first_name=data['name'],
                                            email=data['email'],
                                            password=password,
                                            related_with='artists')

        artist = Artist.objects.create(user=new_user,
                                       salon=salon,
                                       lng=salon.lng,
                                       lat=salon.lat,
                                       description=data['description'],
                                       mobile_number=salon.mobile_number,
                                       style=data['style'],
                                       is_activated=True)
        new_artist_to_salon(salon.user, new_user, password)

        if my_file:

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(my_file).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(10))
            path = '/{0}/artists/{1}/avatar/{2}.jpeg'.format(MEDIA_FOLDER, str(artist.id), hash_name)
            full_path = '{0}artists/{1}/avatar/{2}.jpeg'.format(MEDIA_ROOT, str(artist.id), hash_name)

            #if the folder doesn't exist, create one
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)
            else:
                shutil.rmtree(d)
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
            im.save(full_path, 'JPEG')
            artist.avatar = path
            artist.save()

        return artist


class UploadListing(forms.Form):

    artist = forms.ChoiceField(widget=forms.Select())
    title = forms.CharField(required=True, widget=forms.TextInput())
    description = forms.CharField(required=True, widget=forms.Textarea(attrs={'placeholder': _('Enter description here.')}))
    price = forms.CharField(required=True, widget=forms.NumberInput())
    tags = forms.CharField(required=True, widget=forms.TextInput())
    duration = forms.ChoiceField(widget=forms.Select(), choices=DURATION)
    gender = forms.ChoiceField(widget=forms.RadioSelect(), choices=((0, 'Male'), (2, 'Female')))
    cover = forms.CharField(required=False, widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Listing

    def __init__(self, salon, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UploadListing, self).__init__(*args, **kwargs)
        artists = Artist.objects.filter(salon=salon, is_activated=True, waiting_for_hired=False, waiting_for_fired=False)

        choices = ((0, 'Choose artist'),)
        for artist in artists:
            choices = choices + ((artist.id, artist.user.first_name),)
        self.fields['artist'].choices = choices

    def clean_cover(self):
        data = self.cleaned_data
        cover = data['cover']
        pictures = self.request.POST.getlist('files')
        if not pictures:
            raise forms.ValidationError(_('Please upload a valid images.'))

        return cover

    def clean_price(self):
        data = self.cleaned_data
        price = data['price']
        if not (len(price) in range(5) and price.isdigit()):
            raise forms.ValidationError(_('Please enter a valid price.'))

        return price

    def clean_artist(self):
        data = self.cleaned_data
        artist = data['artist']

        if int(artist) == 0:
            raise forms.ValidationError(_('Please select artist.'))

        return artist

    def save(self, FILES):

        data = self.cleaned_data
        artist = Artist.objects.get(id=int(data['artist']))
        artist_id = str(data['artist'])
        pictures = FILES.getlist('files')
        hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(6))
        for index, picture in enumerate(pictures):

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(picture).group(2)

            path = '/' + MEDIA_FOLDER + '/artists/' + artist_id + '/listings/' + hash_name + '/'
            if index == int(data["cover"]):

templates/core/about_us.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - About us" %}</title>
{% endblock meta %}

    {% block stylesheet %}
    {% endblock stylesheet %}

    {% block content %}
<div id="content">

    {% if messages %}
    <div class="column">
        {% for message in messages %}
        <ul class="message {% if message.tags %}{{ message.tags }}{% endif %}">
                <li class="tag"></li>
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <div class="about_us video">
<iframe src="//player.vimeo.com/video/107852212" width="1000" height="563" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
    <div class="column">
        <ul class="team about_us">
            <li class="team_box">
                <img src="{{ STATIC_URL }}img/tony.png" alt="Antony Ivanov" title="Antony I" class="photo">
                <p class="name">Antony I</p>
                <p class="cool">{% trans "Pixel ninja" %}</p>
                <p class="responsible">{% trans "Responsible for product and design." %}</p>
            </li>
            <li class="team_box">
                <img src="{{ STATIC_URL }}img/ivo.png" alt="Ivo Tasev" title="Ivo T" class="photo">
                <p class="name">Ivo T</p>
                <p class="cool">{% trans "Plan executer" %}</p>
                <p class="responsible">{% trans "Responsible for technical operations management." %}</p>
            </li>
            <li class="team_box">
                <img src="{{ STATIC_URL }}img/az.png" alt="Georgi Zhuhov" title="Georgi Z" class="photo">
                <p class="name">Georgi Z</p>
                <p class="cool">{% trans "Code warrior" %}</p>
                <p class="responsible">{% trans "Responsible for software development." %}</p>
            </li>
            <li class="team_box">
                <img src="{{ STATIC_URL }}img/nikoleta.png" alt="Nicolette V" title="Nicolette" class="photo">
                <p class="name">Nicolette V</p>
                <p class="cool">{% trans "Sales master" %}</p>
                <p class="responsible">{% trans "Responsible for business development and social media." %}</p>
            </li>
        </ul>
        <form method="POST" action="{% url 'send_feedback' %}" class="box about_us">
            {% csrf_token %}
            <h2>{% trans 'WOULD YOU LIKE TO SAY "HI"?' %}</h2>
            <ul>
                <li>
                    <label for="">{% trans "Name" %}</label>
                    <input type="text" name="name">
                </li>
                <li>
                    <label for="">{% trans "Email" %}</label>
                    <input type="text" name="email">
                </li>
                <li>
                    <label for="">{% trans "Reason" %}</label>
                    <input type="text" name="reason">
                </li>
                <li>
                    <label for="">{% trans "Message" %}</label>
                    <textarea name="message"></textarea>
                </li>
            </ul>
            <input type="submit" value="{% trans 'Send' %}" class="custom_button">
        </form>
    </div>
</div>
    {% endblock content %}
    {% block scripts %}
    {% endblock scripts %}
    </body>
</html>

templates/core/home.html
{% extends "master.html" %}
{% load thumbnail %}
{% load i18n %}

{% block meta %}
    <meta name="keywords" content="beauty salon review, beauty parlour, beauty salon, local beauty salons, salon services, best beauty salon, beauty salon offers, beauty spot, beauty salon pictures, hair and makeup artist">
    <meta name="description" content="Find local beauty salon reviews, as well as hair and makeup artists’ ratings with the best offers and listings. Select your appearance and book online.">
    <meta name="p:domain_verify" content="dd3c87dd4b500e40f50597f8adcb882e"/>
    <meta name="alexaVerifyID" content="yRDVVyCdF0smOdFr9JKECU05BYQ"/>
    <meta name="google-site-verification" content="NcP6g-1vbf8YTwq7KuoQE9glxkThDeQIH_5wJG5H2SM" />
    <meta name="google-site-verification" content="aNPKemu18CaWD6MTSM-KSnWTSFg5HjVvmTzPmXg5lvw" />
    <title>{% trans "Booking platform for top beauty salons and artists|Glamfame" %}</title>
{% endblock meta %}

    {% block stylesheet %}
        <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/jquery-ui.css">
    {% endblock stylesheet %}

    {% block content %}
<div id="content">
    <div class="home">
        <div class="column clear">
            <h1 class="text big">{% trans "DO YOU WANT TO GLAM YOURSELF?" %}</h1>
            <h2 class="text">{% trans "BROWSE MULTIPLE LISTINGS, OFFERED BY TOP HAIR, NAILS AND MAKEUP ARTISTS" %}</h2>
            <div class="container">
                <form method="GET" action="/result">
                    <div class="picker"><div class="icon calendar"></div><span>{% trans "Date" %}</span></div>
                    <div class="picker"><div class="icon time"></div><span>{% trans "Time" %}</span></div>
                    <div class="picker"><div class="icon service"></div><span>{% trans "Service" %}</span></div>
                    <div class="location"><div class="icon i_location"></div><input type="text"></div>
                    <input type="hidden" id="id_date" name="date" value="0">
                    <input type="hidden" id="id_time" name="hour" value="-1">
                    <input type="hidden" id="id_service" name="q" value="hair nails make up">
                    <input type="hidden" id="id_lat" name="lat">
                    <input type="hidden" id="id_lng" name="lng">
                    <input type="submit" class="custom_button" value="GO">
                </form>
            </div>
            <div class="trendy"><span class="arrow_down"></span><span class="arrow_down"></span>{% trans "OR CHECK WHAT IS TRENDY RIGHT NOW" %}<span class="arrow_down"></span><span class="arrow_down"></span></div>
        </div>
    </div>
    <div class="column">
        <ul class="gallery col_4">
            {% for listing in listings %}
                <li class="pic_view">
                    <ul>
                        <li class="picture">
                        <a href="{% url 'listing' listing.id listing.title %}">
                            {% thumbnail listing.get_picture "240x143" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{ listing.title }}" width="240" height="143">
                            {% empty %}
                                <img src="{{ STATIC_URL }}/img/listing_placeholder.png" alt="{{ listing.title }}" width="240" height="143">
                            {% endthumbnail %}
                            <div class="overlay"></div>
                        </a>
                        </li>
                        <li class="text">
                            <div class="title">{{ listing.title }}</div>
                            <div class="info">
                                <div class="heart">{{ listing.likes }}</div>
                                <div class="price">{{ listing.get_currency_display }} {{ listing.price|floatformat:-3 }}</div>
                                <div class="comments">{{ listing.comments }}</div>
                            </div>
                        </li>
                        <li class="artist">
                        <a href="{% url 'profile_artist' listing.artist_id listing.artist.user.first_name %}">
                            {% thumbnail listing.artist.get_avatar "60x60" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{ listing.artist.user.first_name }}" width="60" height="60">
                            {% empty %}
                                <img src="{{ STATIC_URL }}img/default.png" alt="{{ listing.artist.user.first_name }}" width="60" height="60">
                            {% endthumbnail %}
                        </a>
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="select_date index date home" style="display: none;">
    <div class="container">
        <div class="class_date" style="position: relative; width: 100%; height: 100%">
            <div class="datepicker_container">
                <div id="datepicker_view"></div>
            </div>
        </div>
    </div>
</div>

<div class="select_date index time home" style="display: none;">
    <div class="container">
        <div class="class_date" style="position: relative; width: 100%; height: 100%">
            <div class="time_container">
                <div class="header">{% trans "SELECT HOUR" %}<a href="javascript:;">+</a></div>
                <ul class="col col_0">
                    <li>8:00AM</li>
                    <li>8:30AM</li>
                    <li>9:00AM</li>
                    <li>9:30AM</li>
                    <li>10:00AM</li>
                    <li>10:30AM</li>
                </ul>
                <ul class="col col_1">
                    <li>11:00AM</li>
                    <li>11:30AM</li>
                    <li>12:00PM</li>
                    <li>12:30PM</li>
                    <li>1:00PM</li>
                    <li>1:30PM</li>
                </ul>
                <ul class="col col_2">
                    <li>2:00PM</li>
                    <li>2:30PM</li>
                    <li>3:00PM</li>
                    <li>3:30PM</li>
                    <li>4:00PM</li>
                    <li>4:30PM</li>
                </ul>
                <ul class="col col_3">
                    <li>5:00PM</li>
                    <li>5:30PM</li>
                    <li>6:00PM</li>
                    <li>6:30PM</li>
                    <li>7:00PM</li>
                    <li>7:30PM</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="select_date index service" style="display: none;">
    <div class="container">
        <div id="date" style="position: relative; width: 100%; height: 100%">
            <div class="time_container">
                <div class="header">{% trans "SELECT SERVICE" %}<a href="javascript:;">+</a></div>
                <ul>
                    <li>{% trans "Hair" %}</li>
                    <li>{% trans "Nails" %}</li>
                    <li>{% trans "Make Up" %}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
    {% endblock content %}
    {% block scripts %}
    <script src="https://j.maxmind.com/app/geoip.js"></script>
    <script src="{{STATIC_URL}}js/ui.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;sensor=false"></script>
    <script type="text/javascript">
        var geo_lat, geo_lng;

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success, fail,{timeout:2000});
        } else {
            fail();
        }

        function success(position) {
            geo_lat = position.coords.latitude;
            geo_lng = position.coords.longitude;
            get_address(geo_lat,geo_lng);
        }

        function fail(){
            geo_lat = geoip_latitude();
            geo_lng = geoip_longitude();
            get_address(geo_lat,geo_lng);
        }

        function get_address(lat,lng){
            $.getJSON('https://maps.googleapis.com/maps/api/geocode/json?latlng=' + lat +
             ',' + lng + '&sensor=false',
            function(data){
                $('.location input').val(data.results['0']['formatted_address']);
                $('#id_lat').val(lat);
                $('#id_lng').val(lng);
            });
        }

        autocomplete = new google.maps.places.Autocomplete(
            ($('.location input')[0]),
            {
                types: ['geocode']
            });

            google.maps.event.addListener(autocomplete, 'place_changed', function() {
                lat = autocomplete.getPlace().geometry.location.lat();
                lng = autocomplete.getPlace().geometry.location.lng();
                $('#id_lat').val(lat);
                $('#id_lng').val(lng);
            });

        $('.picker').click(function(){
            if($(this).index() == 0)
            {
                $('.select_date.date').show();
            }
            else if ($(this).index() == 1)
                $('.select_date.time').show();
            else
                $('.select_date.service').show();
        });

        $(".col li").click(function(){
            $('.col').children().removeClass("active");
            $(this).addClass('active');
            $(this).closest(".select_date").hide();
            $('.picker:eq(1) span').text($(this).text());
            $("#id_time").val($(".col li").index(this))
        });

        $('.select_date').click(function(e){
            if($(e.target).hasClass('select_date'))
                $(this).hide();
        });

        $('.select_date.time .header a').click(function(e){
            $('.select_date.time').hide();
        });
        $('.select_date.service .header a').click(function(e){
            $('.select_date.service').hide();
        });

        $('.select_date.service li').click(function(e){
            $('.select_date.service li').removeClass('active');
            $(this).addClass('active');
            $(this).closest(".select_date").hide();
            $('.picker:eq(2) span').text($(this).text());
            $("#id_service").val($(this).text().toLowerCase())
        });

        function draw_picker(){
            $datapicker = $("#datepicker_view")
            $datapicker.datepicker(
                {
                    minDate: 0,
                    maxDate: "+1M +10D",
                    dayNamesMin: [ "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"],
                    dateFormat: "mm/dd/yy",
                    onSelect: function(dateText, inst){
                        $(".picker:eq(0) span").text($datapicker.val());
                        $(this).closest(".select_date").hide();
                        var temp = new Date(dateText)
                        $("#id_date").val(temp.getTime()/1000);
                    }
                });
            $datapicker.datepicker('show');
        }

        draw_picker()
        $('a.ui-state-default').click(function(){

            $(".select_date.date").hide()
        });
    </script>
    {% endblock scripts %}
    </body>
</html>