glamazer/listings/urls.py
from django.conf.urls import patterns, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^confirm/', 'glamazer.listings.views.confirm', name='booking_confirm'),
    url(r'^check_availability/$', 'glamazer.listings.views.check_availability', name='check_availability'),
    url(r'^edit/(?P<listing_id>.*)$', 'glamazer.listings.views.edit', name='edit_listing'),
    url(r'^delete/(?P<listing_id>.*)$', 'glamazer.listings.views.delete', name='delete_listing'),
    url(r'^activate/(?P<listing_id>.*)$', 'glamazer.listings.views.activate', name='activate_listing'),
    url(r'^(?P<listing_id>.*)/(?P<title>.*)$', 'glamazer.listings.views.show', name='listing'),
)

glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^hairstyle/', 'glamazer.core.views.base', name='hair'),
    url(r'^nails-design/', 'glamazer.core.views.base', name='nails'),
    url(r'^make-up/', 'glamazer.core.views.base', name='make_up'),
    url(r'^style/', 'glamazer.core.views.base', name='style'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^terms/', TemplateView.as_view(template_name="core/terms.html"), name='terms'),
    url(r'^imprint/', TemplateView.as_view(template_name="core/imprint.html"), name='imprint'),
    url(r'^privacy/', TemplateView.as_view(template_name="core/privacy.html"), name='privacy'),
    url(r'^faq/', TemplateView.as_view(template_name="core/faq.html"), name='faq'),
    url(r'^about_us/', TemplateView.as_view(template_name="core/about_us.html"), name='about_us'),
    url(r'^contacts/', TemplateView.as_view(template_name="core/contact_us.html"), name='contacts'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^salons/', include('glamazer.salons.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^widget/', include('glamazer.widget.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^get_hint/', 'glamazer.core.views.get_hint', name='get_hint'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='paypal_payment'),
    url(r'^send_feedback/$', 'glamazer.users.views.send_feedback', name='send_feedback'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/listings/models.py
import os

from pyelasticsearch import ElasticSearch

from haystack.utils.geo import Point
from sorl.thumbnail import get_thumbnail

from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save

from glamazer.settings import MEDIA_ROOT, ELASTIC_SEARCH_URL, LISTING_STATUS, CURRENCY
from glamazer.core.helpers import get_rate
from glamazer.core.notifications import new_listing, approved_listing, bad_listing
from glamazer.artists.models import Artist


class Listing(models.Model):
    artist = models.ForeignKey(Artist)
    picture = models.CharField(max_length=128, help_text='The path to the images. Never change it.')
    picture_cover = models.CharField(max_length=128)
    title = models.CharField(max_length=128)
    description = models.TextField()
    currency = models.CharField(max_length=8, choices=CURRENCY, default='USD')
    original_price = models.FloatField()
    price = models.FloatField()
    gender = models.IntegerField(choices=((0, 'Male'), (2, 'Female')))
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    metadata = models.CharField(max_length=16)
    duration = models.IntegerField(default=0, help_text="1800=00:30 | 3600=1:00 | 5400=1:30 | 7200=2:00 | 9000=2:30 | 10800=3:00 | 12600=3:30 | 14400=4:00")
    status = models.IntegerField(default=0, choices=LISTING_STATUS)
    uploaded = models.DateTimeField(auto_now_add=True)
    last_changed = models.DateTimeField(auto_now=True, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_style(self):
        return self.artist.get_style_display()

    def get_picture(self):
        return self.picture_cover

    def get_all_pictures(self):
        pictures = []
        cover = self.picture_cover.split("/")[-1]
        full_path = MEDIA_ROOT + self.picture[7:]
        for p in os.listdir(full_path):
            if not p == cover:
                pictures.append(full_path + p)
        return pictures

    def get_location(self):
        return Point(self.artist.lat, self.artist.lng)

    def get_artist_id(self):
        return self.artist_id

    def get_artist_avatar(self):
        return self.artist.get_avatar()

    def get_artist_name(self):
        return self.artist.get_name()

    def get_salon_id(self):
        return self.artist.salon_id

    def get_salon_avatar(self):
        return self.artist.get_salon_avatar()

    def get_salon_name(self):
        return self.artist.get_salon_name()

    def get_tags(self):
        listings = ListingTags.objects.filter(listing=self).select_related("tags")
        return [x.tags.tag for x in listings]

    def get_rating(self):
        from glamazer.reviews.models import Review
        reviews = Review.objects.select_related().filter(listing=self)
        rate = get_rate(reviews)
        return rate

    def view_all_pictures(self):
        all_pictures = self.get_all_pictures()
        all_pictures.append(self.get_picture())
        thumbs = '<ul>'
        for pic in all_pictures:
            thumbs += '<li><img src="'
            thumbs += get_thumbnail(pic, '240x143', crop='center', quality=99).url
            thumbs += '"/></li>'
        return thumbs

    view_all_pictures.allow_tags = True
    view_all_pictures.short_description = "Pictures"

    def save(self, force_insert=False, force_update=False, **kwargs):
        es = ElasticSearch(ELASTIC_SEARCH_URL)
        if self.id:
            location = self.get_location()
            location_es = "{0},{1}".format(location.y, location.x)
            es.update('glamazer',
                      'modelresult',
                      'listings.listing.{0}'.format(self.id),
                      script="ctx._source.listing_id = listing;" +
                             "ctx._source.artist_id = artist;" +
                             "ctx._source.artist_avatar = artist_avatar;" +
                             "ctx._source.artist_name = artist_name;" +
                             "ctx._source.salon_id = salon;" +
                             "ctx._source.salon_avatar = salon_avatar;" +
                             "ctx._source.salon_name = salon_name;" +
                             "ctx._source.title = title;" +
                             "ctx._source.location = location;" +
                             "ctx._source.description = description;" +
                             "ctx._source.get_picture = get_picture;" +
                             "ctx._source.metadata = metadata;" +
                             "ctx._source.gender = gender;" +
                             "ctx._source.price = price;" +
                             "ctx._source.currency = currency;" +
                             "ctx._source.likes = likes;" +
                             "ctx._source.comments = comments;" +
                             "ctx._source.tags = tags;" +
                             "ctx._source.status = status;" +
                             "ctx._source.style = style;" +
                             "ctx._source.rating = rating",
                      params={
                             'listing': self.id,
                             'artist': self.get_artist_id(),
                             'artist_avatar': self.get_artist_avatar(),
                             'artist_name': self.get_artist_name(),
                             'salon': self.get_salon_id(),
                             'salon_avatar': self.get_salon_avatar(),
                             'salon_name': self.get_salon_name(),
                             'title': self.title,
                             'location': location_es,
                             'description': self.description,
                             'get_picture': self.get_picture(),
                             'metadata': self.metadata,
                             'gender': self.gender,
                             'price': self.price,
                             'currency': self.currency,
                             'likes': self.likes,
                             'comments': self.comments,
                             'tags': self.get_tags(),
                             'status': self.status,
                             'style': self.get_style(),
                             'rating': self.get_rating()
                        })
            super(Listing, self).save(force_insert, force_update)
        else:
            super(Listing, self).save(force_insert, force_update)

            location = self.get_location()
            location_es = "{0},{1}".format(location.y, location.x)
            es.index('glamazer', 'modelresult', {
                'listing_id': self.id,
                'artist_id': self.artist_id,
                'artist_avatar': self.get_artist_avatar(),
                'artist_name': self.get_artist_name(),
                'salon_id': self.get_salon_id(),
                'salon_avatar': self.get_salon_avatar(),
                'salon_name': self.get_salon_name(),
                'title': self.title,
                'location': location_es,
                'description': self.description,
                'get_picture': self.get_picture(),
                'metadata': self.metadata,
                'gender': self.gender,
                'price': self.price,
                'currency': self.currency,
                'likes': self.likes,
                'comments': self.comments,
                'tags': self.get_tags(),
                'status': self.status,
                'style': self.get_style(),
                'rating': self.get_rating()
                }, id='listings.listing.{0}'.format(self.id))
            es.refresh('glamazer')


@receiver(pre_save, sender=Listing)
def listing_change_status(sender, instance, **kwargs):
    if instance.id:
        old = Listing.objects.get(id=instance.id)
        if old.status == 0:
            if instance.status == 1:
                new_listing(instance.artist.user, None, instance)
                approved_listing(instance.artist.user, instance.artist.user, instance)
            else:
                bad_listing(instance.artist.user, instance.artist.user, instance)


class Tags(models.Model):
    tag = models.TextField()


class ListingTags(models.Model):
    listing = models.ForeignKey(Listing)
    tags = models.ForeignKey(Tags)


class ListingView(models.Model):
    listing = models.ForeignKey(Listing)
    date = models.DateField(auto_now_add=True)
    views = models.IntegerField(default=0)

glamazer/listings/forms.py
import string
import random
import os
import base64
import re

from io import BytesIO
from PIL import Image

from django import forms
from django.utils.translation import ugettext as _

from glamazer.core.helpers import get_object_or_None
from glamazer.listings.models import Listing, Tags, ListingTags
from glamazer.settings import MEDIA_ROOT, DURATION


class EditListing(forms.Form):

    title = forms.CharField(required=True, widget=forms.TextInput())
    description = forms.CharField(required=True, widget=forms.TextInput())
    price = forms.CharField(required=True, widget=forms.NumberInput())
    tags = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "listing_edit", "value": " ", "data-option": "LONDON"}))
    duration = forms.ChoiceField(widget=forms.Select(), choices=DURATION)
    cover = forms.CharField(required=False, widget=forms.HiddenInput(), initial=0)
    gender = forms.ChoiceField(widget=forms.RadioSelect(), choices=((0, 'Male'), (2, 'Female')))
    deleted = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Listing

    def clean_price(self):
        data = self.cleaned_data
        price = data['price']
        if not (len(price) in range(5) and price.isdigit()):
            raise forms.ValidationError(_('Please enter a valid price.'))

        return price

    def save(self, listing, FILES):
        data = self.cleaned_data
        pictures = FILES.getlist('files')
        hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(6))

        my_dir = MEDIA_ROOT + listing.picture[7:]

        deletes_files = data['deleted']
        if deletes_files:
            deletes_files = data['deleted'].split(',')[:-1]
            for d in deletes_files:
                os.remove(d)

        os.chdir(my_dir)

        cover = data["cover"]

        artist_id = str(listing.artist_id)

        for index, picture in enumerate(pictures):
            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(picture).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(6))

            if cover.isdigit() and index == int(cover):
                full_path = MEDIA_ROOT + 'artists/' + artist_id + '/listings/' + listing.metadata + '/' + hash_name + '.jpeg'
                cover = full_path
            else:
                full_path = MEDIA_ROOT + 'artists/' + artist_id + '/listings/' + listing.metadata + '/' + hash_name + '.jpeg'

            #if the folder doesn't exist, create on
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file.encode('ascii'))))
            im.save(full_path, 'JPEG')

        ListingTags.objects.filter(listing=listing).delete()
        tags = data['tags'].split(',')
        for tag in tags:
            tag = tag.lower()
            current_tag = get_object_or_None(Tags, tag=tag)
            if not current_tag:
                current_tag = Tags.objects.create(tag=tag)

            ListingTags.objects.create(listing=listing, tags=current_tag)

        if cover:
            listing.picture_cover = cover
        listing.title = data['title']
        listing.description = data['description']
        listing.price = data['price']
        listing.duration = int(data['duration'])
        listing.gender = int(data['gender'])
        listing.save()

        return listing

templates/listings/edit.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Edit Listing" %}</title>
{% endblock meta %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/select2.css">
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/jquery-ui.css">

{% endblock stylesheets %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "EDIT LISTING" %}</span>
    </div>

    <div class="column">
        <form  class="login listing_upload" method="POST" enctype="multipart/form-data" data-fee="{{ fee }}">
            {% csrf_token %}
            <div class="left_wrapper">
                <div class="vertical_box photos">
                    <div class="box_title">{% trans "1. Photos" %}</div>
                    <div class="body">
                        <div id="gallery_preview" class="multiple_listing">
                            <ul>
                                <li class="ready_photo old cover" data-path="{{listing.get_picture}}">
                                    {% thumbnail listing.get_picture "190x125" crop="center" as im %}
                                        <img src="{{ im.url }}" alt="picture" width="190" height="125"/>
                                    {% empty %}
                                        <img src="{{ STATIC_URL }}/img/listing_placeholder.png" alt="picture" width="190" height="125">
                                    {% endthumbnail %}
                                    <ul class="action">
                                        <li class="delete">{% trans "DELETE" %}</li>
                                        <li class="cover_photo">{% trans "COVER PHOTO" %}</li>
                                    </ul>
                                </li>
                                {% if listing.get_all_pictures %}
                                    {% for l in listing.get_all_pictures %}
                                    <li class="ready_photo old" data-path="{{ l }}">
                                        {% thumbnail l "190x125" crop="center" as im %}
                                            <img src="{{ im.url }}" alt="picture" width="190" height="125"/>
                                        {% empty %}
                                            <img src="{{ STATIC_URL }}/img/listing_placeholder.png" alt="picture" width="190" height="125">
                                        {% endthumbnail %}
                                        <ul class="action">
                                            <li class="delete">{% trans "DELETE" %}</li>
                                            <li class="cover_photo">{% trans "COVER PHOTO" %}</li>
                                        </ul>
                                    </li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                        <div class="photos_upload">
                            {% if form.cover.errors %}
                                <div class="wrong_picture">{{ form.cover.errors }}</div>
                            {% endif %}
                            <div class="upload_button">{% trans "Click here to upload picture" %}</div>
                            <input type="file" name="pictures" id="id_picture" class="custom_button active_input" multiple/>
                            {{ form.cover }}
                        </div>
                    </div>
                </div>

                <div class="vertical_box price">
                    <div class="box_title">{% trans "2. Price" %}</div>
                    <div class="body">
                        <div class="price"><label for="" class="main_label">
                            {% if form.price.errors %}
                                {{ form.price.errors }}
                            {% endif %}
                            Price</label><br>
                            <span class="currency">{{ request.user.artist.get_currency_display }}</span>
                            {{ form.price }}
                        </div>
                        <div class="recalculate">
                            {% blocktrans %}
                            Price after fees: {{ request.user.artist.get_currency_display }}<span class="real_price">0</span><br><br>
                            All fees will be paid by the customer.
                            {% endblocktrans %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="vertical_box description">
                <div class="box_title">{% trans "3. Description" %}</div>
                <div class="body">
                    <ul>
                        <li class="label_container"><label for="" class="main_label">
                            {% if form.title.errors %}
                                {{ form.title.errors }}
                            {% endif %}
                            {% trans "Title" %}</label></li>
                        <li>
                            {{ form.title }}
                        </li>
                        <li class="label_container"><label for="" class="main_label">
                            {% if form.description.errors %}
                                {{ form.description.errors }}
                            {% endif %}
                            {% trans "Description" %}</label></li>
                        <li>
                            {{ form.description }}
                        </li>
                        <li class="label_container duration_gender">
                            <div class="duration">
                                <label for="" class="main_label">
                                {% if form.duration.errors %}
                                    {{ form.duration.errors }}
                                {% endif %}
                                {% trans "Duration" %}</label>{{ form.duration }}
                            </div>
                            <div class="gender">
                                <label for="" class="main_label">
                                {% if form.gender.errors %}
                                    {{ form.gender.errors }}
                                {% endif %}{% trans "Type" %}</label>
                                {{ form.gender }}
                            </div>
                        </li>
                        <li class="clear"></li>
                        <li class="label_container"><label for="" class="main_label">
                            {% if form.tags.errors %}
                                {{ form.tags.errors }}
                            {% endif %}
                            {% trans "Tags" %}</label></li>
                        <li class="tags tags_initial" data-initial="{% for t in tags %}{% if forloop.last %}{{t}}{% else %}{{t}},{%endif%}{% endfor %}">
                            {{ form.tags }}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="clear"></div>
            <input type="submit" class="custom_button" value="{% trans 'Save and continue' %}">
        </form>
    </div>
</div>

    {% endblock content %}
    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
        <!--<script src="{{STATIC_URL}}js/preview.js"></script>-->
        <script type="text/javascript" src="{{STATIC_URL}}js/select2.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/upload_listing.js"></script>
    {% endblock scripts %}
</body>
</html>

templates/listings/listings.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Wishlist" %}</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{{ title }}</span>
    </div>

    <div class="column">
            <ul class="gallery col_4">
                {% for listing in listings %}
                <li class="pic_view">
                    <ul>
                        <a href="{% url 'listing' listing.id listing.title %}">
                        <li class="picture">
                            {% thumbnail listing.get_picture "240x143" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{ listing.title }}" width="240" height="143" >
                            {% empty %}
                                <img src="{{ STATIC_URL }}/img/listing_placeholder.png" alt="{{ listing.title }}" width="240" height="143">
                            {% endthumbnail %}
                            <div class="overlay"></div>
                        </li>
                        </a>
                        <li class="text">
                            <div class="title">{{ listing.title }}</div>
                            <div class="info">
                                <div class="heart">{{ listing.likes }}</div>
                                <div class="price">{{ listing.get_currency_display }} {{ listing.price|floatformat:-3 }}</div>
                                <div class="comments">{{ listing.comments }}</div>
                            </div>
                        </li>
                        <li class="artist">
                            <a href="{% url 'profile_artist' listing.artist_id listing.artist.user.first_name %}">
                                {% thumbnail listing.artist.get_avatar "60x60" crop="center" as im %}
                                    <img src="{{ im.url }}" alt="{{ listing.artist.user.first_name }}" width="60" height="60">
                                {% empty %}
                                    <img src="{{ STATIC_URL }}img/default.png" alt="{{ listing.artist.user.first_name }}" width="60" height="60">
                                {% endthumbnail %}
                            </a>
                        </li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}

    {% endblock scripts %}
</body>
</html>