glamazer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', 'glamazer.core.views.home', name='home'),
    url(r'^hairstyle/', 'glamazer.core.views.base', name='hair'),
    url(r'^nails-design/', 'glamazer.core.views.base', name='nails'),
    url(r'^make-up/', 'glamazer.core.views.base', name='make_up'),
    url(r'^style/', 'glamazer.core.views.base', name='style'),
    url(r'^contest/', 'glamazer.core.views.base', name='contest'),
    url(r'^leaderboards/', 'glamazer.core.views.base', name='leaderboards'),
    url(r'^result/', 'glamazer.core.views.search', name='result'),
    url(r'^get_notifications/', 'glamazer.notifications.views.get_notifications', name='short_notifications'),
    url(r'^get_notifications_count/', 'glamazer.notifications.views.get_notification_count', name='notification_count'),
    url(r'^autocomplete_tags/', 'glamazer.core.views.autocomplete_tags', name='autocomplete_tags'),
    url(r'^sign_up/', TemplateView.as_view(template_name="sign_up.html"), name='signup'),
    url(r'^terms/', TemplateView.as_view(template_name="core/terms.html"), name='terms'),
    url(r'^imprint/', TemplateView.as_view(template_name="core/imprint.html"), name='imprint'),
    url(r'^privacy/', TemplateView.as_view(template_name="core/privacy.html"), name='privacy'),
    url(r'^faq/', TemplateView.as_view(template_name="core/faq.html"), name='faq'),
    url(r'^about_us/', TemplateView.as_view(template_name="core/about_us.html"), name='about_us'),
    url(r'^contacts/', TemplateView.as_view(template_name="core/contact_us.html"), name='contacts'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('glamazer.users.urls')),
    url(r'^artists/', include('glamazer.artists.urls')),
    url(r'^salons/', include('glamazer.salons.urls')),
    url(r'^listings/', include('glamazer.listings.urls')),
    url(r'^favorites/', include('glamazer.favorites.urls')),
    url(r'^reviews/', include('glamazer.reviews.urls')),
    url(r'^widget/', include('glamazer.widget.urls')),
    url(r'^success/', 'glamazer.payments.views.success_payment', name='success'),
    url(r'^error/', 'glamazer.payments.views.error_payment', name='error'),
    url(r'^cancel/', 'glamazer.payments.views.cancel_payment', name='cancel'),
    url(r'^get_hint/', 'glamazer.core.views.get_hint', name='get_hint'),
    url(r'^start_payment/', 'glamazer.payments.views.start_payment', name='paypal_payment'),
    url(r'^send_feedback/$', 'glamazer.users.views.send_feedback', name='send_feedback'),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glamazer/users/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^how_it_works/', TemplateView.as_view(template_name="core/how_it_works_users.html"), name='profiles_HIW'),
    url(r'^confirmation/(?P<email_token>.*)$', 'glamazer.users.views.confirmation', name='confirmation'),
    url(r'^change_password/(?P<email_token>.*)$', 'glamazer.users.views.change_password', name='change_password'),
    url(r'^forgotten_password/', 'glamazer.users.views.forgotten_password', name='forgotten_password'),
    url(r'^login/$', 'glamazer.users.views.login', name='login'),
    url(r'^sign_up/$', 'glamazer.users.views.sign_up', name='sign_up'),
    url(r'^logout/$', 'glamazer.users.views.logout_user', name='logout'),
    url(r'^wishlist/$', 'glamazer.users.views.wishlist', name='wishlist'),
    url(r'^followed/$', 'glamazer.users.views.followed', name='followed'),
    url(r'^change_email/$', 'glamazer.users.views.change_email', name='change_email'),
    url(r'^change_password_user/$', 'glamazer.users.views.change_password_user', name='change_password_user'),
    url(r'^sign_up/facebook', 'glamazer.users.views.facebook_registration', name='facebook_sign_up'),
    url(r'^login/facebook', 'glamazer.users.views.facebook_login', name='facebook_login'),
    url(r'^profile/$', 'glamazer.users.views.profile', name='user_profile'),
    url(r'^profile/(?P<user_id>.*)/(?P<name>.*)$', 'glamazer.users.views.profile', name='profile_user'),
    url(r'^settings', 'glamazer.users.views.settings', name='user_settings'),
    url(r'^bookings$', 'glamazer.users.views.bookings', name='profiles_bookings'),
    url(r'^bookings/report', 'glamazer.users.views.report_problem', name='profiles_report_booking'),
    url(r'^cancel', 'glamazer.users.views.cancel', name='booking_cancel'),
    url(r'^notifications/$', 'glamazer.notifications.views.show_notifications', name='user_notifications'),
)

glamazer/booking/models.py
import datetime

from django.db import models
from django.core.urlresolvers import reverse

from glamazer.listings.models import Listing
from glamazer.artists.models import Artist, CancellationPolicy
from glamazer.users.models import Profile
from glamazer.settings import STATUS, CURRENCY


class Booking(models.Model):
    artist = models.ForeignKey(Artist, null=True)
    client = models.ForeignKey(Profile)
    listing = models.ForeignKey(Listing)
    cancellation_policy = models.ForeignKey(CancellationPolicy)
    currency = models.CharField(max_length=8, choices=CURRENCY, default='USD')
    price = models.FloatField(default=0)
    revenue = models.FloatField(default=0)
    title = models.TextField(blank=True, null=True)
    start_time = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)
    comment = models.TextField(blank=True, null=True)
    status = models.IntegerField(default=0, choices=STATUS)
    cancelled_by = models.IntegerField(default=0)
    review_email = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return datetime.datetime.fromtimestamp(self.start_time).strftime('%Y-%m-%d %H:%M:%S')

    def get_status(self):
        return self.get_status_display()

    def artist_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:artists_artist_change"), args=(self.artist_id, )), self.artist.user.first_name)
        return url

    def client_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:users_profile_change"), args=(self.client_id, )), self.client.user.first_name)
        return url

    def listing_link(self):
        url = '<a href="%s">%s</a>' % (reverse(("admin:listings_listing_change"), args=(self.listing_id, )), self.listing.title)
        return url

    artist_link.allow_tags = True
    artist_link.short_description = "Artist"

    client_link.short_description = 'Client'
    client_link.allow_tags = True

    listing_link.allow_tags = True
    listing_link.short_description = "Listing"


class DummyBooking(models.Model):
    artist = models.ForeignKey(Artist)
    client = models.ForeignKey(Profile)
    listing = models.ForeignKey(Listing)
    cancellation_policy = models.ForeignKey(CancellationPolicy)
    currency = models.CharField(max_length=8, choices=CURRENCY, default='USD')
    revenue = models.FloatField(default=0)
    price = models.FloatField(default=0)
    title = models.TextField(blank=True, null=True)
    start_time = models.IntegerField(default=0)
    end_time = models.IntegerField(default=0)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


class ReportedProblems(models.Model):
    _STATUS = ((0, 'Open',), (1, 'In progress',), (2, 'Closed',),)
    artist = models.ForeignKey(Artist, null=True)
    client = models.ForeignKey(Profile, null=True)
    listing = models.ForeignKey(Listing, null=True)
    booking = models.ForeignKey(Booking, null=True)
    comment = models.TextField(blank=True, null=True, default=0)
    created = models.DateTimeField(auto_now_add=True, null=True, default=0)
    sender = models.CharField(max_length=16, default=0, null=True)
    status = models.IntegerField(default=0, choices=_STATUS, null=True)

glamazer/users/models.py
from django.db import models
from django.contrib.auth.models import User

from glamazer.notifications.models import Notification
from glamazer.settings import MEDIA_ROOT, STATIC_ROOT


class Profile(models.Model):

    facebook_id = models.CharField(max_length=20, blank=True, null=True)
    user = models.OneToOneField(User, unique=True)
    avatar = models.CharField(max_length=128, blank=True, null=True)
    auto_created = models.BooleanField(default=False)
    is_activated = models.BooleanField(default=False)
    mobile_number = models.CharField(max_length=128, blank=True, null=True)
    enable_emails = models.BooleanField(default=True)
    enable_sms = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name

    def get_avatar(self):
        if self.avatar:
            return MEDIA_ROOT + self.avatar[7:]
        else:
            return ''

    def get_name(self):
        return self.user.first_name

    def get_notification_count(self):
        '''get only the notifications count, whithout evaluate the query'''
        notification_count = Notification.objects.filter(receiver=self.user, is_readed=False).count()
        return notification_count

    def get_notifications(self, limit=0):
        '''get all notifications for current instance and make them readed'''
        if limit:
            notifications = Notification.objects.filter(receiver=self.user)[:limit]
        else:
            notifications = Notification.objects.filter(receiver=self.user)

        return notifications

    def get_avatar_tag(self):
        if self.avatar:
            return '<img src="%s" style="border-radius: 999px" />' % self.avatar
        else:
            return '<img src="%s" style="border-radius: 999px" />' % (STATIC_ROOT+'/img/default.png')

    get_avatar_tag.short_description = 'Avatar'
    get_avatar_tag.allow_tags = True

    get_name.allow_tags = True
    get_name.short_description = "Name"


class ConfirmationToken(models.Model):
    user = models.ForeignKey(User)
    email_token = models.CharField(max_length=32)


class PasswordToken(models.Model):
    email = models.CharField(max_length=255)
    email_token = models.CharField(max_length=255)


related_with = models.CharField(max_length=16, blank=True, null=True)
related_with.contribute_to_class(User, 'related_with')

glamazer/users/forms.py
import string
import random
import os
import shutil
import base64
import re

from io import BytesIO
from PIL import Image

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.forms import ModelForm
from django.utils.translation import ugettext as _

from glamazer.users.models import Profile
from glamazer.core.helpers import get_object_or_None
from glamazer.settings import MEDIA_FOLDER, MEDIA_ROOT


class ProfileForm(ModelForm):

    name = forms.CharField(required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())
    password = forms.CharField(widget=(forms.PasswordInput()))
    confirm_password = forms.CharField(widget=(forms.PasswordInput()))

    class Meta:
        model = Profile
        fields = ['confirm_password', ]

    def clean_email(self):

        email = self.cleaned_data['email']

        check_email = get_object_or_None(User, email=email)

        if check_email and get_object_or_None(Profile, user=check_email, auto_created=True):
            raise forms.ValidationError(
                _("A user associated with this email address already exists"))

        return email

    def clean_password(self):

        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not password == confirm_password:
            raise forms.ValidationError(_("Password mismatch"))

        elif len(password) < 6:
            raise forms.ValidationError(_("Password is too short (6 symbols)"))

        elif password.isalpha() or password.isdigit():
            raise forms.ValidationError(_("Password should contain at least one alphabetic and one non-alphabetic character"))

        return password

    def save(self):

        data = self.cleaned_data

        check_email = get_object_or_None(User, email=data['email'])

        if not check_email:
            username = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(16))

            new_user = User.objects.create_user(username=username,
                                                first_name=data['name'],
                                                email=data['email'],
                                                password=data['password'],
                                                related_with="profiles")
            profile = Profile.objects.create(user=new_user)
        else:
            check_email.first_name = data['name']
            check_email.set_password(data['password'])
            check_email.save()

            profile = Profile.objects.get(user=check_email)
            profile.auto_created = False
            profile.save()

        return profile


class LoginUserForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput())
    password = forms.CharField(
        required=True, widget=forms.PasswordInput(render_value=False))
    remember_me = forms.BooleanField(required=False)

    def clean(self):

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            if user and user.is_active:
                return self.cleaned_data

        raise forms.ValidationError("Invalid login details")


class ChangePasswordForm(forms.Form):

    new_password = forms.CharField(required=True, widget=forms.PasswordInput(
        render_value=False))
    confirm_password = forms.CharField(required=True, widget=forms.PasswordInput(
        render_value=False))

    def clean(self):

        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if new_password != confirm_password:
            raise forms.ValidationError(_("Password mismatch"))

        return self.cleaned_data


class ForgottenPasswordForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput())


class EditProfile(ModelForm):

    name = forms.CharField(required=True, widget=forms.TextInput())
    avatar = forms.ImageField(required=False, widget=forms.FileInput())
    cropped_image = forms.CharField(required=False, widget=forms.HiddenInput())
    mobile_number = forms.CharField(required=False, widget=forms.TextInput())
    enable_emails = forms.BooleanField(required=False)
    enable_sms = forms.BooleanField(required=False)

    class Meta:
        model = Profile
        exclude = ('user',)

    def clean_enable_sms(self):
        profile = self.instance
        enable_sms = self.cleaned_data.get('enable_sms')
        if enable_sms and not (profile.mobile_number or self.cleaned_data.get('mobile_number')):
            raise forms.ValidationError(_("Please enter your phone in order to receive sms."))

        return enable_sms

    def save(self):

        profile = self.instance
        user = profile.user
        data = self.cleaned_data

        user.first_name = data['name']
        user.save()
        profile.mobile_number = data['mobile_number']
        profile.enable_emails = data['enable_emails']
        profile.enable_sms = data['enable_sms']
        profile.save()

        my_file = data['cropped_image']

        if my_file:

            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            my_file = dataUrlPattern.match(my_file).group(2)

            hash_name = ''.join(random.choice(string.ascii_lowercase + string.digits)for x in range(10))
            path = '/' + MEDIA_FOLDER + '/users/' + str(profile.id) + '/avatar/' + hash_name + '.jpeg'
            full_path = MEDIA_ROOT + 'users/' + str(profile.id) + '/avatar/' + hash_name + '.jpeg'
            profile.avatar = path
            profile.save()

            #if the folder doesn't exist, create one
            d = os.path.dirname(full_path)
            if not os.path.exists(d):
                os.makedirs(d)
            else:
                shutil.rmtree(d)
                os.makedirs(d)

            im = Image.open(BytesIO(base64.b64decode(my_file)))
            im.save(full_path, 'JPEG')

        return profile

templates/user/followed.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Followed" %}</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "FOLLOWED ARTISTS" %}</span>
    </div>

    <div class="column">
            <ul class="gallery">
                {% for listing in listings %}
                <li class="pic_view">
                    <ul>
                        <li class="picture">
                            <a href="{% url 'listing' listing.id listing.title %}">
                            {% thumbnail listing.get_picture "240x143" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{ listing.title }}" width="240" height="143">
                            {% empty %}
                                <img src="{{ STATIC_URL }}/img/listing_placeholder.png" alt="{{ listing.title }}" width="240" height="143">
                            {% endthumbnail %}
                                <div class="overlay"></div>
                            </a>
                        </li>
                        <li class="text">
                            <div class="title">{{ listing.title }}</div>
                            <div class="info">
                                <div class="heart">{{ listing.likes }}</div>
                                <div class="price">{{ listing.get_currency_display }} {{ listing.price|floatformat:-3 }}</div>
                                <div class="comments">{{ listing.comments }}</div>
                            </div>
                        </li>
                        <li class="artist">
                        <a href="{% url 'profile_artist' listing.artist_id listing.artist.user.first_name %}">
                            {% thumbnail listing.artist.get_avatar "60x60" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{listing.artist.user.first_name}}" width="60" height="60">
                            {% empty %}
                                <img src="{{ STATIC_URL }}img/default.png" alt="{{listing.artist.user.first_name}}" width="60" height="60">
                            {% endthumbnail %}
                        </a>
                        </li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}

    {% endblock scripts %}
</body>
</html>

templates/user/forgotten_password.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Forgotten Password" %}</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "FORGOTTEN PASSWORD" %}</span>
    </div>

    <div class="column">
        <div class="forms">
            <form class="login" method="post" action=".">
                <div class="instruction">{% trans "Please submit your email address. You will receive an email with further instructions how to create new password for your account." %}</div>
                {% csrf_token %}
                <ul>
                    <li>
                        {% if form.email.errors %}
                            {{ form.email.errors }}
                        {% endif %}
                        <label for="" class="main_label"></label></li>
                    <li>
                        {{ form.email }}
                    </li>

                    <li>
                        <input type="submit" value="Submit">
                    </li>

                </ul>
            </form>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
    {% endblock scripts %}
</body>
</html>

templates/user/login.html
{% extends "master.html" %}
{% load i18n %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Login" %}</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "LOGIN" %}</span>
    </div>

    <div class="column">
        <div class="forms">
            <form id="form_1" class="login" method="post" action=".">
                {% csrf_token %}
                    {% if user_form.errors %}
                        <ul class="errorlist"><li><ul class="errorlist"><li>{% trans "Invalid login details" %}</li></ul></li></ul>
                    {% endif %}
                <ul>
                    <li>
                        {% if user_form.email.errors %}
                            {{ user_form.email.errors }}
                        {% endif %}
                        <label for="" class="main_label">{% trans "Email" %}</label></li>
                    <li>
                        {{ user_form.email }}
                    </li>
                    <li>
                        {% if user_form.password.errors %}
                            {{ user_form.password.errors }}
                        {% endif %}
                        <label for="" class="main_label">{% trans "Password" %}</label></li>
                    <li>
                        {{ user_form.password }}
                    </li>
                    <li>

                        <ul>
                            <li>{{ user_form.remember_me }} <label for="id_remember_me" class="main_label">{% trans "Remember Me" %}</label></li>
                            <li><a href="{% url 'forgotten_password' %}">{% trans "Forgot your password?" %}</a></li>
                        </ul>

                        <input type="submit" name="log_user" value="{% trans 'Log In' %}">
                    </li>
                    <li class="or">
                        <div></div>
                        <div class="or"> {% trans "OR" %} </div>
                    </li>
                    <li class="facebook">
                        <div class="facebook_icon"></div>
                        <input type="button" value="{% trans 'Log in with Facebook' %}" onclick="log_me()">
                        <div class="fb-login-button" data-perms="email" data-scope="email" data-max-rows="1" data-show-faces="false"></div>
                        <div id="fb-root"></div>
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}
        <script src="https://connect.facebook.net/en_US/all.js"></script>
        <script src="{{STATIC_URL}}js/facebook.js"></script>
        <script src="{{STATIC_URL}}js/error.js"></script>
    {% endblock scripts %}
</body>
</html>

templates/user/settings.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Settings" %}</title>
{% endblock meta %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/select2.css">
    <link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}/css/imgselectarea.css">
{% endblock stylesheets %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "SETTINGS" %}</span>
    </div>

    <div class="column">
        <div class="head">
            <ul>
                <li><a class="active">{% trans "PROFILE" %}</a></li>
            </ul>
        </div>

        <form method="POST" action="{{ request.get_full_path }}" id="settings" enctype="multipart/form-data" class="user">
            {% csrf_token %}
            <ul class="settings">
                <li class="profile_picture">
                    <ul>
                        <li class="avatar">
                            <div>
                                {% thumbnail profile.get_avatar "150x150" crop="center" as im %}
                                    <img src="{{ im.url }}" width="150" height="150">
                                {% empty %}
                                    <img src="{{ STATIC_URL }}img/default.png" width="150" height="150">
                                {% endthumbnail %}
                            </div>
                        </li>
                        <li>
                            <div class="small_button gray change hidden">{% trans "Change" %}</div>
                            {{ form.avatar }}
                            {{ form.cropped_image }}
                        </li>
                    </ul>
                </li>
                <li>
                    <ul class="left profile">
                        <li class="name">
                            <label for="" class="main_label">
                                {% if form.name.errors %}
                                    {{ form.name.errors }}
                                {% endif %}
                                {% trans "Name" %}
                            </label>
                            {{ form.name }}
                        </li>
                        <li class="number">
                            <label for="" class="main_label">
                            {% if form.mobile_number.errors %}
                                {{ form.mobile_number.errors }}
                            {% endif %}
                            {% if form.enable_sms.errors %}
                                {{ form.enable_sms.errors }}
                            {% endif %}
                            {% trans "Phone" %}
                            </label>
                            {{ form.mobile_number }}
                        </li>
                        <li class="notifications">
                            <label for="" class="main_label">{% trans "Notifications" %}</label>
                            <ul>
                                <li>
                                    {{ form.enable_emails }}
                                    <label for="id_enable_emails" class="main_label">{% trans "Receive notifications for booking request and other activities via email" %}</label>
                                </li>
                                <li>
                                    {{ form.enable_sms }}
                                    <label for="id_enable_sms" class="main_label">{% trans "Receive notifications for booking request and other activities via text messages" %}</label>
                                </li>
                            </ul>
                        </li>
                        <li class="setting_buttons">
                            <div class="small_button gray edit">{% trans "Edit" %}</div>
                            <div class="small_button gray cancel hidden">{% trans "Cancel" %}</div>
                            <input type="submit" value="{% trans 'Save' %}" class="small_button green save hidden">
                        </li>
                    </ul>
                </li>
            </ul>
        </form>

    </div>
</div>

    {% endblock content %}

    {% block scripts %}
        <script src="{{STATIC_URL}}js/error.js"></script>
        <script src="{{STATIC_URL}}js/preview.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}js/imgSelectArea.js"></script>
        <script type="text/javascript">
            $("#settings input").attr("disabled", "disabled");

            $(".edit").click(function(){
                $(".small_button.change, .small_button.save, .small_button.cancel").removeClass("hidden");
                $(".edit").addClass("hidden");
                $("#settings input, #settings textarea").removeAttr("disabled", "disabled");
            });
            $(".small_button.cancel").click(function(){location.reload();});

            $(".message .close a").click(function(){
                $("ul.message").remove();
            });
            if($(".number .errorlist").length){
                $("#id_enable_sms").attr('checked', false);
            }
        </script>
    {% endblock scripts %}
</body>
</html>

templates/user/wishlist.html
{% extends "master.html" %}
{% load i18n %}
{% load thumbnail %}

{% block meta %}
    <title>{% trans "Glamfame – Booking platform for top salons and beauty artists - Wishlist" %}</title>
{% endblock meta %}

    {% block content %}
<div id="content">
    <div class="header">
        <span>{% trans "WISHLIST" %}</span>
    </div>

    <div class="column">
            <ul class="gallery">
                {% for listing in listings %}
                <li class="pic_view">
                    <ul>
                        <li class="picture">
                            <a href="{% url 'listing' listing.id listing.title %}">
                            {% thumbnail listing.get_picture "240x143" crop="center" as im %}
                                <img src="{{ im.url }}" alt="{{ listing.title }}" width="240" height="143">
                            {% empty %}
                                <img src="{{ STATIC_URL }}/img/listing_placeholder.png" alt="{{ listing.title }}" width="240" height="143">
                            {% endthumbnail %}
                                <div class="overlay"></div>
                            </a>
                        </li>
                        <li class="text">
                            <div class="title">{{ listing.title }}</div>
                            <div class="info">
                                <div class="heart">{{ listing.likes }}</div>
                                <div class="price">{{ listing.get_currency_display }} {{ listing.price|floatformat:-3 }}</div>
                                <div class="comments">{{ listing.comments }}</div>
                            </div>
                        </li>
                        <li class="artist">
                            <a href="{% url 'profile_artist' listing.artist_id listing.artist.user.first_name %}">
                            {% thumbnail listing.artist.get_avatar "60x60" crop="center" as im %}
                                <img src="{{ im.url }}" alt="artist" width="60" height="60">
                            {% empty %}
                                <img src="{{ STATIC_URL }}img/default.png" alt="artist" width="60" height="60">
                            {% endthumbnail %}
                            </a>
                        </li>
                    </ul>
                </li>
                {% endfor %}
            </ul>
            </div>
        </div>
    </div>
</div>

    {% endblock content %}

    {% block scripts %}

    {% endblock scripts %}
</body>
</html>